import React from "react";
import Head from "next/head";
import { MdShoppingBag } from "react-icons/md";

import Styles from "../../styles/Header.module.scss";

export function Header() {
  return (
    <>
      <Head>
        <title>Sal da Terra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={Styles.header}>
        <div>
          <MdShoppingBag size={50} color="white" />
          <h1>ST</h1>
        </div>
      </header>
    </>
  );
}
