import React from "react";
import Head from "next/head";
import Image from "next/image";

export function Header() {
  return (
    <>
      <Head>
        <title>Sal da Terra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </header>
    </>
  );
}
