import React from "react";
import Head from "next/head";
import Image from "next/image";

import Styles from "@/styles/Header.module.scss";

export function Header() {
  return (
    <>
      <Head>
        <title>Sal da Terra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={Styles.header}>
        <div className={Styles.headerWrapper}>
          <Image
            unoptimized={true}
            src="logo.svg"
            alt="Logo"
            width={60}
            height={60}
          />
        </div>
      </header>
    </>
  );
}
